package Helpers;

public class BaseVariables {
	public static int ImplicitWait;
	public static String BrowserName, URL, DownloadPath, Username, Password, DownloadFile=null;
	public static String DB_HostName, DB_Port, DB_Name, DB_Username, DB_Password, DB_TableName, DB_URL;
	public static String OrderNo, TOS_Ref, ColName, EleemntText, ContainerNo, Status, Laden, delexp, acpVal, cp, exp6, End_Date, OrderNumber; 
	public static int ScreenIndexNo=0, exp, exp2, exp5, vq, vr, row, ResponseCode, BeforeRowCount=0, AfterRowCount=0, IndexNo=0; 
	public static String BeforeSortCellValue=null, AfterSortCellValue=null, SelectService=null, Entered_Date=null, LoginName=null;
	public static String StartTime=null, SearchStartTime=null, SearchEndTime=null, ServiceDate=null, CurrentDate=null, Container_No;
	public static String win1=null, win2=null, InGateDisplay=null, NewRateValue=null, OrderDate=null, OrderAmount=null, StorageCharges;
	public static int Act, AddlServiceRowsCount, PlusIconSize=0, RowCount=0, SumRate=0, ServiceRow=0, AccessIndexNo ,AccessCbNo;
	public static double ChargeVal;
	public static String ChargeAdjustmentDate=null, FromDate=null, Charge_Adjustment_Amount=null, In_Gate_Date=null, ZoneName=null; 
	public static String[] win=new String[5];
	public static String API_URL=null, Authorization=null, ContentType=null, UserAgent=null, Empty=null, FRS=null, TerminalId=null;
	public static String Accept=null, Host=null, ConnectionName=null, ContentLength=null, Size=null, Type=null, Contract=null;
	public static String Sender=null, Receiver=null, CreatedBy=null, OMS_Ref=null, ContainerNumber=null, UpdateContainerNo=null;
	public static String RequestBody=null, Response=null, CreateEvent=null, UpdateEvent=null,SeqNo1=null, SeqNo2=null, UserName=null;
	public static String CustomerRef=null, AcceptanceRef=null, ReleaseRef=null, Booked_Rail_Date=null, Booked_Rail_Time=null;
	public static String BookedRailDate=null, BookedRailTime=null, BookedRailInDate=null, CustomerName, TerminalCode=null;
	public static String Time_Stamp_Date=null, TimeStampDate=null, Time_Stamp_Time=null, TimeStampTime=null, CustomerAcNo=null;
	public static String UnitCode=null, InGateDate=null, OmsReference=null, ElementText1=null, ElementText2=null, OrderRemarks=null;
	public static String StorageStartDate, StorageEndDate,TotalStorageDays, StartDate, EndDate=null, TariffCode=null, TariffName=null; 
	public static String MSG , ContNo, Acceptance_Ref, Customer_Ref, Tariff_Code=null, RoleDes=null, FirstName=null, PageNo= null;
	public static String TerminalName=null, SANTOX_Code=null, TaxId=null, TaxDescription=null, ElementText=null, RoleName=null;
	public static String StateName=null, ServiceName=null, NomainalAccountCode=null, OutGateDate=null, BookedRailOutDate=null;
	public static int Response_Code=0, CompanyIndexNo=0, RowNo=0, ReasonCodeRow=0, AddRemarksRow=0; 
	public static String ReasonCode=null, ReasonDescription=null, FileName=null, OldValue=null, NewValue=null, TimeStamp=null;
	public static String PWD=null, MinPassword=null, MaxPassword=null, NewPassword=null, TemplateNameValue=null, ToDate=null;
	public static String ChangedData=null, ChangedDate=null, ChangedBy=null, ApprovedBy=null, Document_Name=null, CostCenterCode=null;
	public static String OrderNumber1=null, OrderNumber2=null, ReasonName=null, Booked_Rail_Out_Date=null, Booked_Rail_In_Date=null;
	public static String CorrectDateFormat, EnteredText, Grid_Billing_Period, OrderAdjustmentDate=null, InvoiceNumber=null;
	public static String[] InvoiceNumbers, GridBillingPeriod, InvoiceBillingPeriod=null, per;
	public static String GridBillPeriod[], GridSplitFromDate[], GridSplitToDate[], InvoiceSplitFromDate[], InvoiceSplitToDate[];
	public static String GridFromDate, GridFdd, GridFmm, GridFyy, GridToDate, GridTdd, GridTmm, GridTyy, InvoiceBillingPeriodFromDate; 
	public static String InvFdd, InvFmm, InvFyy, InvoiceBillingPeriodToDate, InvTdd, InvTmm, InvTyy, FirstTariffCode=null;
	public static String SubAccountCode=null, SubAccountName=null, GpRule=null, GpRuleName=null, BusinessVertical=null;
	public static String NomainalAccountName=null, BeforeText, BeforeTextValue, DeptCode=null, DeptName=null, EnteredBankName=null;
	public static String CostCentreCode=null, CostCentreName=null, ToastMsg=null, Percentage=null, EnteredAddress=null;
	public static String EnteredBankAddress=null, ItemDescription=null, Quantity=null, Rate=null, TotalAmt=null, ContinentName=null;
	public static String VAT_Amount=null,TotalPrice=null, CurrencyCode=null, CurrencySymbol=null, Original_InvoiceDate=null;
	public static String OriginalInvoiceBillingPeriod=null, Original_InvoiceNo=null, Invoice_Date=null, Purchase_Order_No=null;
	public static String BillingPeriod=null, BankDetails=null, BankName1=null, BankName2=null, BankCity=null, OriginalInvNo=null;
	public static String BankCountry=null, BankPinCode=null, BankAccountNo=null, ContainerSize=null, ContainerType=null;
	public static String TransportModeIn=null, TransportModeOut=null, LadenEmpty=null, InvAmtwithoutVAT=null, Total_with_VAT=null;	 
	public static Float Total_Including_VAT=null, Total_Excluding_VAT=null, TaxAmount=null, TaxPercentage=null;
	public static String InvPrpChargeAdjAmt=null, InvoiceNo, InvTerminal, InvItemDesc, InvTotalExcVat, InvTax, InvTotal, RptTerminal;
	public static String RptItemDesc,RptTotalExcVat, RptTax, RptTotal=null, Entity=null, CompanyName=null, DesignationName=null;
	public static String TariffEndDate=null, ValidateTariffEndDate=null, EnterTariffEndDate=null, Before_Text_Value, ChargeName=null; 
	public static String WidgetTitle=null, BeforeDragAndDropWidgetLocation=null, BeforeResizeWidth=null, BeforeResizeHeight=null;
	public static String  AfterResizeWidth=null, AfterResizeHeight=null, CustomerCode=null, CreditDays=null, CountryName=null;
	public static String[] WidgetListOfUser1 = new String[5];
	public static String[] WidgetListOfUser2 = new String[5];
	public static String SecondTariffCode=null, CompanyCode=null, ActiveStatus=null, CityName=null, Out_Gate_Date=null;
	public static Float Storage_Fee=null, Lift_Fee=null, Additional_ServiceFee=null, TotalChargeAdjustmentAmount=null, Total_Charge;
	public static String TotalCharge=null, Charge_Value=null, BusinessVerticalName=null, StorageDD, CurrentDD, CutOffTime=null;
	public static Double ChargeValue=null;
	public static int AddService_RowCount=0, ChargeAdjustment_RowCount=0, Days=0;
	public static String ExpStorageDays, ActStorageDays;
	
}
